name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
          args: --timeout=30m --config=.golangci.yaml --issues-exit-code=2 -v

