name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, "**"]

concurrency:
  group: ${{ github.workflow}}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
        id: go
      - name: test to see if we can pull docker container from ghcr.io
        run: docker pull ghcr.io/permify/permify

      - name: mod verify
        run: go mod verify

      - name: mod download
        run: go mod download

      - name: ensure compilation
        run: go build

      - name: Use the reusable workflow for test
        # Use the retry action
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 120
          command: go test ./... -v -cover 
#
#      - name: test
#        run: 
#        with:
#          max_attempts: 3
#          retry_on: error
#          timeout_seconds: 5

